### ISSUE TITLE
May I use this theme?

### ISSUE THREAD

**Issue by rawrgulmuffins** [KenMercusLai/BT3-Flat#4]
Hello KenMercusLai,

The BT3-Flat theme is awesome and easily the best Pelican theme out there. I'm not sure if I can use it for my personal site, however, since there is no license included with the theme. Did you intend for the theme to be used by others or is it on github for viewing purposes only?

**Comment by KenMercusLai** [comment]
Hi, Alex,

Of course you can use it for whatever you want. I’m not a professional developer & have zero knowledge about the license, any idea if I just want to make it free to use for non-commercial purpose?


−−−
Ken Mercus Lai 赖健
✉ ken.mercus.lai@gmail.com
✆ +86 18682286570

**Comment by rawrgulmuffins** [comment]
So these apply to the US, EU, and Japan (mostly). I'm not sure about other countries.

[If you want people to use your code but you don't want it to be used for commercial purposes than  CC-NC-ND (Creative Commons - non-commercial - no derivates)](https://programmers.stackexchange.com/questions/32444/opensource-noncommercial-license).

[Here's some more information if you're interested.](https://www.quora.com/What-is-the-best-free-for-non-commercial-use-license-to-use-for-an-open-source-project)

Also, I don't think you can produce something of this quality and not call yourself a developer at this point. =P

**Comment by rawrgulmuffins** [comment]
I will also add that if you don't add a FOSS license (MIT, BSD, Apache, FireFox) than most people will not able able to use your theme. the CC-NC-ND license will also mean that the script can't legally be allowed in the Pelican-Themes (if the owners are paying attention to the licenses).

**Comment by KenMercusLai** [comment]
I add Gpl3 as license , is this ok?

**Comment by rawrgulmuffins** [comment]
Yes, totally acceptable License if you want your code to be free and open source, must be attributed to you, and also has large barriers to profiting off your work.

**Comment by KenMercusLai** [comment]
I think I have to really pay some attention to licenses.
