### ISSUE TITLE
CRITICAL: 'articles_page' is undefined

### ISSUE THREAD

**Issue by rhester72** [KenMercusLai/BT3-Flat#9]
Having the same issue as noted in [Issue 1](https://github.com/KenMercusLai/BT3-Flat/issues/1) with a brand-new checkout and using your configuration (only having modified the plugin path and the path to your theme).  Any direction on where I might look?  This is on Pelican 3.5.0.

**Comment by KenMercusLai** [comment]
I checked out the latest version and used the config file which I pasted, no problem for me with pelican 3.5.0

can you share some any output message?
